sudo: required
dist: xenial
language: php
env:
    - V8VER=7.5

php:
  - 7.2
  - 7.3
  - 7.4

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_install:
    - sudo add-apt-repository ppa:stesie/libv8 -y
    - sudo apt-get update -yqq
    - sudo apt-get install -y libv8-${V8VER}-dev

before_script:
  - git clone https://github.com/phpv8/v8js.git
  - cd v8js && phpize && ./configure LDFLAGS="-lstdc++" --with-v8js=/opt/libv8-${V8VER} && $(MAKE) -j3 && $(MAKE) install install && cd ..
  - echo "extension = v8js.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit

